THEVOICE-6 migrate from tslint to eslint
oakslab/ooo-config-examples pull request #12
Opened 2020-10-06 15:00 UTC by henckellbach

It's time to move away from TSLint _(deprecated)_ to ESLint and revive this repo!

2020-10-19 14:53 UTC, Ketcap commented on common/.eslintrc.js
> +    'react/react-in-jsx-scope': 'off', // Allow not importing React as Next imports it automatically
shouldn't this override on the project-specific base?

2021-01-05 08:39 UTC, alizhdanov commented
Looks good. The only thing I'd keep more generic config in the `common` folder and in the `frontend` folder extend it and add all frontend related things.

2021-01-05 17:47 UTC, alizhdanov requested changes
Almost perfect 👍

2021-01-05 17:47 UTC, alizhdanov commented on frontend/.eslintrc.js
> +  extends: [
I'd extend from common config and remove duplicity. Check my [PR](https://github.com/oakslab/ooo-config-examples/pull/8/files#diff-552c24c518fbc7b1401230074f9350f29c3cce7744ae9431173f2dc16d81f745R8)

2021-01-05 17:47 UTC, alizhdanov commented on package.json
>    "author": "OAK'S LAB",
I think you forgot to install dependencies 🤔 E.g. `typescript-eslint`.

2021-01-05 17:47 UTC, alizhdanov commented on package.json
> +  "version": "0.0.8",
Let's make a minor release (0.1.0) as it has some breaking changes.

2021-01-28 12:28 UTC, alizhdanov approved these changes

2021-01-28 12:35 UTC, merged